### ISSUE TITLE
Running tests with Docker

### ISSUE THREAD

**Issue by olesiaMartushkanova** [alexej-strelzow/testcafe-cucumber-typescript#2]
Hi,

I came across your project and it's working perfectly for me on my local! 
But I would also like to know how to run tests with Docker?

I assume that provided docker-image from testcafe is not going to work for this project (https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html) because you are using cucumber.js to run tests.

Could you please advise a solution?

Thank you

**Comment by alexej-strelzow** [comment]
Hi,

I'm happy that it works perfectly for you :)

Do you want to target an existing (deployed) system OR do you want to run the app in docker as well and then execute the tests against that app - as part of CI/CD for 1 app?

Both versions are possible. I did not use that image, but made my own one. If you can tell me your use case I can try to provide an image ;-)

**Comment by olesiaMartushkanova** [comment]
I want to run tests as part of CI process, we are using concourse for it and docker.
But for now  I just want to make my tests running on my local with Docker to test that all steps are working as expected.

If you could share your image that would be great!

Currently, I'm using general node image and here are what I have in my Dockerfile:
```
FROM node:latest

WORKDIR /

COPY package.json .
COPY package.json yarn.lock
COPY tsconfig.json tsconfig.json

RUN apt-get -y update
RUN apt-get install -y nodejs

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN yarn add -D testcafe
RUN yarn add -D cucumber
RUN yarn cross-env NODE_ENV=test TS_NODE_PROJECT='./tsconfig.json' ./node_modules/cucumber/bin/cucumber-js src/features --require-module ts-node/register --require 'src/**/*.ts' -f json:./reports/cucumber_report.json
```

Getting this error: ENOENT: no such file or directory, open '/src/reports/cucumber_report.json'

**Comment by olesiaMartushkanova** [comment]
SO I have improved my dockerfile:
```
FROM node:latest

COPY ./config ./config
COPY  ./reports ./reports
COPY ./src ./src
COPY package.json .
COPY yarn.lock yarn.lock
COPY tsconfig.json tsconfig.json

RUN apt-get -y update
RUN apt-get install -y nodejs

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN yarn add -D testcafe
RUN yarn add -D cucumber

RUN TS_NODE_PROJECT='./tsconfig.json' ./node_modules/cucumber/bin/cucumber-js src/features --require-module ts-node/register --require 'src/**/*.ts'
```

and now I'm getting:
`GeneralError: Unable to find the browser. "chrome" is not a browser alias or path to an executable file.`

could you please share how do you install browser in docker container @alexej-strelzow ?

**Comment by alexej-strelzow** [comment]
Hi, 
this works for me:

Dockerfile
```
FROM node:12-stretch

# Install basic software
RUN apt-get update \
    && apt-get install -y wget

# Set the Chrome repo
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

# Install Chrome
RUN apt-get update && apt-get -y install google-chrome-stable
RUN google-chrome --version

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm i
RUN npm i -g testcafe@1.7.0

# add app
COPY . /usr/src/app

# run E2E tests
# ***Note***: chrome:headless has known bug regarding downloading artifacts (https://bugs.chromium.org/p/chromium/issues/detail?id=696481)
ENV BROWSER chrome:headless
ENV BROWSER_FLAGS --no-sandbox
ENV TEST_FAIL_FILE=fail.txt

RUN chmod a+x /usr/src/app/e2e-testing.sh
RUN /usr/src/app/e2e-testing.sh
```

e2e-testing.sh
```
#!/bin/bash

npm run test

#ls -lah /usr/src/app/e2e/reports/

if [ -e "/usr/src/app/reports/${TEST_FAIL_FILE}" ]; then
    echo "One or more E2E-Tests failed!"
    echo "!!! TERMINATING BUILD !!!"
    exit 1
fi
```

lmk how it goes
