### ISSUE TITLE
It would be great if I can run each feature in a different browser and parallelize them.

### ISSUE THREAD

**Issue by srodriguezg** [alexej-strelzow/testcafe-cucumber-typescript#3]
I am using your library as the basis for my project, I really like it and it is very good but I would like it to be possible to execute each feature in a different browser and to be able to parallelize their execution. At the moment I have a suite of 20 features, when I run these, they all run in the same browser and this does not open a different browser instance.

**Comment by srodriguezg** [comment]
Hi?

**Comment by alexej-strelzow** [comment]
Hi, @srodriguezg sorry for the late reply. 

Regarding running them in parallel. Short answer: now it works - you made me do it ;-)
Long answer:
Cucumber comes with a parallel switch, still experimental, https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#parallel-experimental. You can try it out like so: `npm run tests:parallel`. The resulting JSON report (reports/cucumber_report.json) contains the aggregated results of each runner. After the process terminates the HTML + junit report get generated. At the moment the metadata get lost in parallel mode (as they are process specific), but I will fix that soon (probably by writing that info into a shared (physical) JSON file.

I hope that solves the issue?

// old answer below

Without cucumbers parallel switch (not recommended):
You can easily do that on Scenario basis - although that is not what you asked for.
With TestCafe 1.9 you have multi window support (https://github.com/DevExpress/testcafe/blob/master/CHANGELOG.md#v190-2020-8-6).

When you pull the latest version you can try this GIVEN in github.ts:
```
Given(/^I open the GitHub page$/, async function (this: Ctx) {
  const t = await this.getTestController();
  await t.openWindow(githubPage.url());
  await t.getCurrentWindow().maximizeWindow();
});
```

At the end of the test you would also have to make sure to close the window.
I did not try that, but maybe you can do sth like that (not sure if it works on feature-level):
1. tag all your feature files with a unique tag
2. Provide a Before and After Hook in your step_definitions and there select the respective feature tag
3. In Before you open a new window and maximize it
4. In After you close the window

BR
Alexej
