### ISSUE TITLE
'LIVE_MODE' is not recognized as an internal or external command and 'TAGS' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by iam-amanxz** [alexej-strelzow/testcafe-cucumber-typescript#4]
I am trying to run the tests with tests:live:win and tests:live:wip:win and getting following error on console

![image](https://user-images.githubusercontent.com/50168544/114813639-2ab20400-9dd0-11eb-8522-6f9199847af3.png)

**Comment by alexej-strelzow** [comment]
Hi,
env vars cannot be like that on windows. For this to work you'd have to install e.g. "cross-env" and set the env var with it.

E.g. "cross-env TAGS=@wip npm run tests:live:win"

I will put it in in near future. But that would fix your issue.

**Comment by iam-amanxz** [comment]
Hi,

Thanks for the help. That worked fine. 🙂
